# Generated by Django 5.0.3 on 2024-03-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=10)),
                ('subject_teacher', models.CharField(max_length=20)),
                ('total_students', models.IntegerField()),
                ('subject_fee', models.IntegerField()),
            ],
        ),
    ]
